name: 'Wait and download artifacts'
description: 'Wait and download artifacts from GitHub'
inputs:
  name:
    description: 'Name of the artifact to download'
    required: true
    default: 'name'
  path:
    description: 'Path to download artifacts'
    required: true
    default: '.'
runs:
  using: "node20"
  # Have to wrap it in an action to make ACTIONS_RUNTIME_TOKEN available.
  main: '../../../download_step/wait_and_download.mjs'
