name: Web Server and Client steps
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

concurrency:
  group: client_server
  cancel-in-progress: true

jobs:
  http_server:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Start server
      run: |
        echo "Starting HTTP server"
        npx -y http-server . &

    - name: Download file from server
      run: |
        until curl -sSf http://localhost:8080 >/dev/null; do
          sleep 0.2
        done
        curl http://localhost:8080/test.html

  reader:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Wait for artifact
      run: |
        mkdir -p downloads
        cd downloads
        echo "Waiting for artifact"
        while ! gh run download ${GITHUB_RUN_ID} -n test-artifact; do
          echo "Waiting for artifact"
          sleep 1
        done
        echo "Artifact downloaded"
        ls -l .
        cat test-artifact
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Download artifact with action
      uses: actions/download-artifact@v4
      with:
        name: test-artifact
        path: foo

  writer:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create artifact
      run: |
        echo "Hello, World!" > test-artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-artifact
        path: test-artifact
